model:
  target: src.models.transformerwrapper.AutoencoderWanTransformer
  base_learning_rate: 1.0e-4
  params:
    base_learning_rate: ${model.base_learning_rate} 
    image_key: video
    input_dim: 5
    use_discriminator: False
    freeze_encoder: True
    freeze_quant_conv: True
    freeze_decoder: True

    use_reference: True
    skip_decoder_attention: False
    gradient_checkpointing: False

    chunk: 5
    num_layers: 10
    num_heads: 12
    head_dim: 128
    pretrained: False
    reusing: True

    use_lora: False
    inference_w_dropout: False
    dropout_p: 0.0

    ckpt_path: # enter ckpt path here

    lossconfig:
      target: src.modules.losses.LPIPSWithDiscriminator3D
      params:
        disc_start: 1
        kl_weight: 0.0
        disc_weight: 0.0
        perceptual_weight: 1.0